# Generated by Django 4.1.5 on 2023-01-30 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Tag name')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('deadline', models.DateTimeField(verbose_name='Deadline')),
                ('is_mark', models.BooleanField(default=False, verbose_name='Execution mark')),
                ('tags', models.ManyToManyField(related_name='tasks', to='schedule.tag')),
            ],
            options={
                'ordering': ['is_mark', '-create_date'],
            },
        ),
    ]
