# Generated by Django 4.1.5 on 2023-01-24 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_created=True)),
                ('content', models.TextField()),
                ('deadline', models.DateField(auto_now_add=True)),
                ('marks', models.BooleanField()),
                ('tags', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.tag')),
            ],
            options={
                'ordering': ['create_date', '-marks'],
            },
        ),
    ]
